FROM postgres:12-alpine

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

COPY db/ .
RUN cat ./create_db.sql \
  ./rls.sql \
  ./users.seed.sql \
	> /docker-entrypoint-initdb.d/init.sql
	